Moved to CentOS because of the compilation error
# cxx/lib/common/CMakeFiles/bcl2fastq_common.dir/build.make:57: recipe for target 'cxx/lib/common/CMakeFiles/bcl2fastq_common.dir/Logger.cpp.o' failed